# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class addEdit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(787, 412)
        self.tableWidget_edit = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget_edit.setGeometry(QtCore.QRect(10, 10, 761, 192))
        self.tableWidget_edit.setObjectName("tableWidget_edit")
        self.tableWidget_edit.setColumnCount(0)
        self.tableWidget_edit.setRowCount(0)
        self.btn_edit = QtWidgets.QPushButton(parent=Form)
        self.btn_edit.setGeometry(QtCore.QRect(640, 200, 131, 31))
        self.btn_edit.setObjectName("btn_edit")
        self.tableWidget_add = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget_add.setGeometry(QtCore.QRect(20, 280, 751, 71))
        self.tableWidget_add.setObjectName("tableWidget_add")
        self.tableWidget_add.setColumnCount(0)
        self.tableWidget_add.setRowCount(0)
        self.btn_add = QtWidgets.QPushButton(parent=Form)
        self.btn_add.setGeometry(QtCore.QRect(640, 350, 131, 31))
        self.btn_add.setObjectName("btn_add")
        self.btn_exit = QtWidgets.QPushButton(parent=Form)
        self.btn_exit.setGeometry(QtCore.QRect(30, 370, 75, 23))
        self.btn_exit.setObjectName("btn_exit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_edit.setText(_translate("Form", "сохранить изменения"))
        self.btn_add.setText(_translate("Form", "добавить запись"))
        self.btn_exit.setText(_translate("Form", "вернуться"))
